// The Region's seed data: the Institutions and Contacts the CRM starts from, and the researched
// competitor product data. Loaded before the page's script; it only defines data.
// scripts/extract-crm-data.js reads this file too, so keep each list a plain literal.

const SEED_INSTITUTIONS = [
  // UNIVERSITIES
  {id:'uva',name:'University of Amsterdam',short:'UvA',type:'university',city:'Amsterdam',website:'https://www.uva.nl',founded:1632,description:'One of Europe\'s largest research universities with ~30,000 students.',researchDirector:'Peter-Paul Verbeek',libraryDirector:'Carlos Reijnen'},
  {id:'vu',name:'VU Amsterdam',short:'VU',type:'university',city:'Amsterdam',website:'https://www.vu.nl',founded:1880,description:'Vrije Universiteit Amsterdam — values-driven research university.',researchDirector:'Jeroen Geurts',libraryDirector:'Hilde van Wijngaarden'},
  {id:'eur',name:'Erasmus University Rotterdam',short:'EUR',type:'university',city:'Rotterdam',website:'https://www.eur.nl',founded:1913,description:'Known for economics, law, and medical sciences.',researchDirector:'Jantine Schuit',libraryDirector:'Lucinda Jones'},
  {id:'uu',name:'Utrecht University',short:'UU',type:'university',city:'Utrecht',website:'https://www.uu.nl',founded:1636,description:'Consistently ranked among the top European universities.',researchDirector:'Ted Sanders',libraryDirector:'Matthijs van Otegem'},
  {id:'leiden',name:'Leiden University',short:'LU',type:'university',city:'Leiden',website:'https://www.universiteitleiden.nl',founded:1575,description:'The Netherlands\' oldest university, founded in 1575.',researchDirector:'Sarah de Rijcke',libraryDirector:'Kurt De Belder'},
  {id:'rug',name:'University of Groningen',short:'RUG',type:'university',city:'Groningen',website:'https://www.rug.nl',founded:1614,description:'Comprehensive research university in the north of the Netherlands.',researchDirector:'Jacquelien Scherpen',libraryDirector:'Marjolein Nieboer'},
  {id:'ru',name:'Radboud University',short:'RU',type:'university',city:'Nijmegen',website:'https://www.ru.nl',founded:1923,description:'Catholic university with strong science and medical faculties.',researchDirector:'José Sanders',libraryDirector:'Charo Narvaez'},
  {id:'tudelft',name:'TU Delft',short:'TU Delft',type:'university',city:'Delft',website:'https://www.tudelft.nl',founded:1842,description:'Netherlands\' largest and oldest technical university.',researchDirector:'Hester Bijl',libraryDirector:'Irene Haslinger'},
  {id:'tue',name:'Eindhoven University of Technology',short:'TU/e',type:'university',city:'Eindhoven',website:'https://www.tue.nl',founded:1956,description:'Technology and science university with strong industry ties.',researchDirector:'Silvia Lenaerts',libraryDirector:'Corry Wouters'},
  {id:'ut',name:'University of Twente',short:'UT',type:'university',city:'Enschede',website:'https://www.utwente.nl',founded:1961,description:'Entrepreneurial university focusing on technology and society.',researchDirector:'Tom Veldkamp',libraryDirector:'Mert Alberts'},
  {id:'tiu',name:'Tilburg University',short:'TiU',type:'university',city:'Tilburg',website:'https://www.tilburguniversity.edu',founded:1927,description:'Specialising in social sciences, humanities, law and economics.',researchDirector:'Antoinette de Bont',libraryDirector:'Corné van Nispen'},
  {id:'um',name:'Maastricht University',short:'UM',type:'university',city:'Maastricht',website:'https://www.maastrichtuniversity.nl',founded:1976,description:'Known for problem-based learning and European focus.',researchDirector:'Jan Smits',libraryDirector:'Claudia van Oppen'},
  {id:'wur',name:'Wageningen University & Research',short:'WUR',type:'university',city:'Wageningen',website:'https://www.wur.nl',founded:1918,description:'Top-ranked globally for agriculture and life sciences.',researchDirector:'Carolien Kroeze',libraryDirector:'Martijn van den Heuvel'},
  {id:'ou',name:'Open Universiteit',short:'OU',type:'university',city:'Heerlen',website:'https://www.ou.nl',founded:1984,description:'Distance learning university open to all.',researchDirector:'Theo Bastiaens',libraryDirector:''},

  // MEDICAL CENTERS
  {id:'aumc',name:'Amsterdam UMC',short:'AUMC',type:'medical',city:'Amsterdam',website:'https://www.amsterdamumc.org',founded:2018,description:'Merger of AMC and VUmc — one of Europe\'s leading academic medical centres.',researchDirector:'Elga de Vries',libraryDirector:''},
  {id:'erasmusmc',name:'Erasmus MC',short:'EMC',type:'medical',city:'Rotterdam',website:'https://www.erasmusmc.nl',founded:1966,description:'University Medical Centre Rotterdam; largest in the Netherlands.',researchDirector:'Stefan Sleijfer',libraryDirector:'Adrian Cohen'},
  {id:'umcutrecht',name:'UMC Utrecht',short:'UMCU',type:'medical',city:'Utrecht',website:'https://www.umcutrecht.nl',founded:1955,description:'Academic medical centre affiliated with Utrecht University.',researchDirector:'Elly Hol',libraryDirector:''},
  {id:'lumc',name:'Leiden University Medical Centre',short:'LUMC',type:'medical',city:'Leiden',website:'https://www.lumc.nl',founded:1816,description:'One of eight UMCs in the Netherlands, affiliated with Leiden University.',researchDirector:'Maartje Huijbers',libraryDirector:'Ilse Jansma'},
  {id:'umcg',name:'University Medical Centre Groningen',short:'UMCG',type:'medical',city:'Groningen',website:'https://www.umcg.nl',founded:1797,description:'The largest employer in the north of the Netherlands.',researchDirector:'Jochen Mierau',libraryDirector:'Peter Fokkens'},
  {id:'radboudumc',name:'Radboudumc',short:'Radboudumc',type:'medical',city:'Nijmegen',website:'https://www.radboudumc.nl',founded:1956,description:'Academic medical centre affiliated with Radboud University.',researchDirector:'Jan Smit',libraryDirector:''},
  {id:'mumc',name:'Maastricht UMC+',short:'MUMC+',type:'medical',city:'Maastricht',website:'https://www.mumc.nl',founded:1966,description:'Academic hospital linked to Maastricht University.',researchDirector:'Annemie Schols',libraryDirector:'Claudia van Oppen'},
  {id:'maxima',name:'Princess Máxima Center',short:'PMC',type:'medical',city:'Utrecht',website:'https://www.prinsesmaximacentrum.nl',founded:2018,description:'National centre for paediatric oncology in the Netherlands.',researchDirector:'René Medema',libraryDirector:''},
  {id:'nki',name:'Netherlands Cancer Institute',short:'NKI',type:'medical',city:'Amsterdam',website:'https://www.nki.nl',founded:1913,description:'Comprehensive cancer centre combining clinic and research.',researchDirector:'Thijn Brummelkamp',libraryDirector:''},

  // RESEARCH INSTITUTIONS
  {id:'nwo',name:'Dutch Research Council',short:'NWO',type:'research',city:'The Hague',website:'https://www.nwo.nl',founded:1950,description:'Netherlands Organisation for Scientific Research — main public funder of scientific research.',researchDirector:'Marcel Levi',libraryDirector:''},
  {id:'tno',name:'TNO',short:'TNO',type:'research',city:'The Hague',website:'https://www.tno.nl',founded:1932,description:'Netherlands Organisation for Applied Scientific Research — independent research organisation.',researchDirector:'Christa Hooijer',libraryDirector:''},
  {id:'knaw',name:'Royal Netherlands Academy of Arts and Sciences',short:'KNAW',type:'research',city:'Amsterdam',website:'https://www.knaw.nl',founded:1808,description:'Advisory body to government and the main Dutch learned society.',researchDirector:'Geert de Snoo',libraryDirector:''},
  {id:'hubrecht',name:'Hubrecht Institute',short:'Hubrecht',type:'research',city:'Utrecht',website:'https://www.hubrecht.eu',founded:1916,description:'KNAW institute for developmental and stem cell biology.',researchDirector:'Geert Kops',libraryDirector:''},
  {id:'nin',name:'Netherlands Institute for Neuroscience',short:'NIN',type:'research',city:'Amsterdam',website:'https://nin.nl',founded:1985,description:'KNAW institute for brain research.',researchDirector:'Christiaan Levelt',libraryDirector:''},
  {id:'rivm',name:'RIVM',short:'RIVM',type:'research',city:'Bilthoven',website:'https://www.rivm.nl',founded:1909,description:'National Institute for Public Health and the Environment.',researchDirector:'Isabel Arends',libraryDirector:''},
  {id:'cwi',name:'Centrum Wiskunde & Informatica',short:'CWI',type:'research',city:'Amsterdam',website:'https://www.cwi.nl',founded:1946,description:'National research institute for mathematics and computer science.',researchDirector:'Vanessa Evers',libraryDirector:''},
  {id:'esc',name:'Netherlands eScience Center',short:'eScienceCenter',type:'research',city:'Amsterdam',website:'https://www.esciencecenter.nl',founded:2012,description:'National centre for the development and use of research software.',researchDirector:'Menno Rasch',libraryDirector:''},
  {id:'deltares',name:'Deltares',short:'Deltares',type:'research',city:'Delft',website:'https://www.deltares.nl',founded:2008,description:'Independent institute for applied research on water and subsurface.',researchDirector:'Henriette Otter',libraryDirector:''},
  {id:'sron',name:'SRON Netherlands Institute for Space Research',short:'SRON',type:'research',city:'Leiden',website:'https://www.sron.nl',founded:1983,description:'National expertise institute for space research.',researchDirector:'Michael Wise',libraryDirector:''},
  {id:'nikhef',name:'Nikhef',short:'Nikhef',type:'research',city:'Amsterdam',website:'https://www.nikhef.nl',founded:1975,description:'National institute for subatomic physics.',researchDirector:'Jorgen D\'Hondt',libraryDirector:''},
  {id:'mmc',type:'medical',name:'Máxima Medical Centre',short:'MMC',city:'Veldhoven',website:'https://www.mmc.nl',founded:'2015',description:'Major teaching hospital in the Eindhoven-Veldhoven region; partner to TU/e and significant clinical research centre.',researchDirector:'',libraryDirector:''},
  {id:'sanquin',type:'medical',name:'Sanquin Research',short:'Sanquin',city:'Amsterdam',website:'https://www.sanquin.nl',founded:'1998',description:'National blood supply organisation and internationally recognised research institute for blood-related disorders, immunology and haematology.',researchDirector:'',libraryDirector:''},
  {id:'aighd',type:'medical',name:'Amsterdam Institute for Global Health and Development',short:'AIGHD',city:'Amsterdam',website:'https://www.aighd.org',founded:'2009',description:'Joint initiative of UvA and AMC; leading global health research with strong focus on infectious disease in low- and middle-income countries.',researchDirector:'',libraryDirector:''},
  {id:'astron',type:'research',name:'ASTRON — Netherlands Institute for Radio Astronomy',short:'ASTRON',city:'Dwingeloo',website:'https://www.astron.nl',founded:'1949',description:'Operates the LOFAR radio telescope and is a core partner in the Square Kilometre Array (SKA); world leader in radio astronomy technology.',researchDirector:'',libraryDirector:''},
  {id:'nioz',type:'research',name:'NIOZ Royal Netherlands Institute for Sea Research',short:'NIOZ',city:'Den Burg (Texel)',website:'https://www.nioz.nl',founded:'1876',description:'Leading European marine and climate research institute; operates two campuses and major research vessels across the North Sea and beyond.',researchDirector:'',libraryDirector:''},
  {id:'knmi',type:'research',name:'KNMI — Royal Netherlands Meteorological Institute',short:'KNMI',city:'De Bilt',website:'https://www.knmi.nl',founded:'1854',description:'National weather, climate and seismological authority; major contributor to IPCC and EU climate science infrastructure.',researchDirector:'',libraryDirector:''},
  {id:'naturalis',type:'research',name:'Naturalis Biodiversity Center',short:'Naturalis',city:'Leiden',website:'https://www.naturalis.nl',founded:'1820',description:'National natural history museum and internationally recognised research institute for biodiversity science; hosts one of the world\'s largest natural history collections.',researchDirector:'',libraryDirector:''},
  {id:'nlr',type:'research',name:'NLR — Netherlands Aerospace Centre',short:'NLR',city:'Amsterdam',website:'https://www.nlr.nl',founded:'1919',description:'National applied research centre for aerospace; serves aviation industry, defence and space sector with specialised testing and certification capability.',researchDirector:'',libraryDirector:''},
  {id:'pbl',type:'research',name:'PBL Netherlands Environmental Assessment Agency',short:'PBL',city:'The Hague',website:'https://www.pbl.nl',founded:'2008',description:'Independent government research agency providing scientific analysis of environmental, nature and spatial planning policy; advises Dutch and EU governments.',researchDirector:'',libraryDirector:''},
  {id:'cpb',type:'research',name:'CPB Netherlands Bureau for Economic Policy Analysis',short:'CPB',city:'The Hague',website:'https://www.cpb.nl',founded:'1945',description:'World-renowned macro-economic research bureau advising the Dutch government; its economic forecasts underpin the national budget process.',researchDirector:'',libraryDirector:''},
  {id:'rathenau',type:'research',name:'Rathenau Institute',short:'Rathenau',city:'The Hague',website:'https://www.rathenau.nl',founded:'1986',description:'Independent research institute for science, technology and society; advises parliament and government on science policy and the societal impact of new technologies.',researchDirector:'',libraryDirector:''},
  {id:'scp',type:'research',name:'SCP — Netherlands Institute for Social Research',short:'SCP',city:'The Hague',website:'https://www.scp.nl',founded:'1973',description:'Government research institute mapping the social and cultural state of the Netherlands; highly cited in social policy and public governance.',researchDirector:'',libraryDirector:''},
  {id:'clingendael',type:'ngo',name:'Clingendael Institute',short:'Clingendael',city:'The Hague',website:'https://www.clingendael.org',founded:'1983',description:'Netherlands Institute of International Relations; internationally recognised for geopolitical analysis, diplomacy training and foreign policy research.',researchDirector:'',libraryDirector:''},
  {id:'hiil',type:'ngo',name:'HiiL — Hague Institute for Innovation of Law',short:'HiiL',city:'The Hague',website:'https://www.hiil.org',founded:'2005',description:'International organisation measuring and innovating access to justice globally; influential in legal research and justice system reform.',researchDirector:'',libraryDirector:''},
  {id:'oxfamnovib',type:'ngo',name:'Oxfam Novib',short:'Oxfam Novib',city:'The Hague',website:'https://www.oxfamnovib.nl',founded:'1956',description:'Major Dutch development organisation with substantial research capacity in inequality, humanitarian response and sustainable development.',researchDirector:'',libraryDirector:''},
  {id:'icj',type:'ngo',name:'International Court of Justice',short:'ICJ',city:'The Hague',website:'https://www.icj-cij.org',founded:'1945',description:'Principal judicial organ of the UN; strategically located in The Hague and central to international law research and practice in the Netherlands.',researchDirector:'',libraryDirector:''},
  {id:'iiss',type:'ngo',name:'Asser Institute',short:'Asser',city:'The Hague',website:'https://www.asser.nl',founded:'1965',description:'Leading international research institute for private international law, international humanitarian law and European law; partner to Dutch and EU legal institutions.',researchDirector:'',libraryDirector:''},
  {id:'zonmw',type:'ngo',name:'ZonMw',short:'ZonMw',city:'The Hague',website:'https://www.zonmw.nl',founded:'1998',description:'The Netherlands Organisation for Health Research and Development; major public funder of health research and care innovation, commissioned by the Ministry of Health and NWO.',researchDirector:'',libraryDirector:''},
  {id:'niod',type:'research',name:'NIOD Institute for War, Holocaust and Genocide Studies',short:'NIOD',city:'Amsterdam',website:'https://www.niod.nl',founded:'1945',description:'KNAW national institute for WWII, Holocaust and genocide research with independent publication output.',researchDirector:'',libraryDirector:''},
  {id:'huygens',type:'research',name:'Huygens Institute for the History of the Netherlands',short:'Huygens ING',city:'Amsterdam',website:'https://www.huygens.knaw.nl',founded:'2008',description:'KNAW institute for Dutch history and digital humanities research.',researchDirector:'',libraryDirector:''},
  {id:'iish',type:'research',name:'International Institute of Social History',short:'IISH',city:'Amsterdam',website:'https://iisg.amsterdam',founded:'1935',description:'KNAW institute; globally leading archive and research centre on labour and social history.',researchDirector:'',libraryDirector:''},
  {id:'meertens',type:'research',name:'Meertens Institute',short:'Meertens',city:'Amsterdam',website:'https://www.meertens.knaw.nl',founded:'1930',description:'KNAW institute for Dutch language, culture and ethnology research.',researchDirector:'',libraryDirector:''},
  {id:'dans',type:'research',name:'DANS — Data Archiving and Networked Services',short:'DANS',city:'The Hague',website:'https://dans.knaw.nl',founded:'2005',description:'Joint KNAW/NWO national institute for research-data archiving and FAIR data services.',researchDirector:'',libraryDirector:''},
  {id:'nioo',type:'research',name:'Netherlands Institute of Ecology (NIOO-KNAW)',short:'NIOO',city:'Wageningen',website:'https://nioo.knaw.nl',founded:'1955',description:'Major KNAW ecology institute publishing 200+ peer-reviewed papers per year.',researchDirector:'',libraryDirector:''},
  {id:'westerdijk',type:'research',name:'Westerdijk Fungal Biodiversity Institute',short:'Westerdijk',city:'Utrecht',website:'https://www.westerdijkinstitute.nl',founded:'1904',description:'KNAW institute; world-renowned fungal culture collection and mycology research.',researchDirector:'',libraryDirector:''},
  {id:'amolf',type:'research',name:'AMOLF',short:'AMOLF',city:'Amsterdam',website:'https://amolf.nl',founded:'1949',description:'NWO-I institute for physics of complex and functional matter, ~200 research staff.',researchDirector:'',libraryDirector:''},
  {id:'arcnl',type:'research',name:'Advanced Research Center for Nanolithography',short:'ARCNL',city:'Amsterdam',website:'https://arcnl.nl',founded:'2014',description:'Public-private (UvA/VU/NWO/ASML) fundamental nanolithography research institute.',researchDirector:'',libraryDirector:''},
  {id:'differ',type:'research',name:'DIFFER — Dutch Institute for Fundamental Energy Research',short:'DIFFER',city:'Eindhoven',website:'https://www.differ.nl',founded:'2012',description:'NWO-I institute for fusion and energy research, ~100 researchers.',researchDirector:'',libraryDirector:''},
  {id:'marin',type:'research',name:'MARIN — Maritime Research Institute Netherlands',short:'MARIN',city:'Wageningen',website:'https://www.marin.nl',founded:'1929',description:'World-leading independent maritime and hydrodynamics research institute.',researchDirector:'',libraryDirector:''},
  {id:'nfi',type:'research',name:'Netherlands Forensic Institute',short:'NFI',city:'The Hague',website:'https://www.forensicinstitute.nl',founded:'1945',description:'National forensic science institute with an active peer-reviewed publication record.',researchDirector:'',libraryDirector:''},
  {id:'wodc',type:'research',name:'WODC — Research and Documentation Centre',short:'WODC',city:'The Hague',website:'https://www.wodc.nl',founded:'1973',description:'Independent research institute of the Ministry of Justice and Security, ~90 reports per year.',researchDirector:'',libraryDirector:''},
  {id:'trimbos',type:'ngo',name:'Trimbos Institute',short:'Trimbos',city:'Utrecht',website:'https://www.trimbos.nl',founded:'1996',description:'Independent national institute for mental health, addiction and drugs research.',researchDirector:'',libraryDirector:''},
  {id:'nivel',type:'ngo',name:'Nivel — Netherlands Institute for Health Services Research',short:'Nivel',city:'Utrecht',website:'https://www.nivel.nl',founded:'1966',description:'Independent nonprofit health services research institute, ~110 scientific researchers.',researchDirector:'',libraryDirector:''},
  {id:'ihedelft',type:'university',name:'IHE Delft Institute for Water Education',short:'IHE Delft',city:'Delft',website:'https://www.un-ihe.org',founded:'2003',description:'UNESCO category-2 institute; largest international graduate water-education and research institute, PhD-granting.',researchDirector:'',libraryDirector:''},
  {id:'mpi',type:'research',name:'Max Planck Institute for Psycholinguistics',short:'MPI',city:'Nijmegen',website:'https://www.mpi.nl',founded:'1980',description:'Major international Max Planck institute dedicated to psycholinguistics, closely tied to Radboud University.',researchDirector:'',libraryDirector:''},
  {id:'wetsus',type:'research',name:'Wetsus — European Centre of Excellence for Sustainable Water Technology',short:'Wetsus',city:'Leeuwarden',website:'https://www.wetsus.nl',founded:'2003',description:'Nonprofit research centre with a large public-private research programme and own PhD/postdoc research staff.',researchDirector:'',libraryDirector:''}
];

const SEED_CONTACTS = [
  {id:'c001',instId:'uva',first:'Peter-Paul',last:'Verbeek',title:'Rector Magnificus',dept:'Executive Board',email:'p.p.c.c.verbeek@uva.nl',phone:'+31 6 143 30 896',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Rector Magnificus; Anniek de Ruijter appointed successor from 1 Sep 2026. Source: uva.nl'},
  {id:'c002',instId:'uva',first:'Vinod',last:'Subramaniam',title:'President of the Executive Board',dept:'Executive Board',email:'v.subramaniam@uva.nl',phone:'+31 6 514 71 804',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Strategy, HR, communication, external relations, impact. Source: uva.nl'},
  {id:'c003',instId:'uva',first:'Richard',last:'Goldstein',title:'Vice-President of the Executive Board',dept:'Executive Board',email:'r.goldstein@uva.nl',phone:'+31 6 390 12 136',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Finance, ICT, facilities management. Source: uva.nl'},
  {id:'c004',instId:'uva',first:'Carlos',last:'Reijnen',title:'Director of the University Library',dept:'University Library (UBA)',email:'C.W.C.Reijnen@uva.nl',phone:'+31 20 525 2310',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: uba.uva.nl'},
  {id:'c005',instId:'uva',first:'Charmian',last:'Fokkens',title:'Head of Education & Research Support',dept:'University Library (UBA)',email:'c.v.fokkens@uva.nl',phone:'+31 6 42 04 95 67',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: uba.uva.nl'},
  {id:'c006',instId:'vu',first:'Jeroen',last:'Geurts',title:'Rector Magnificus',dept:'Executive Board',email:'j.j.g.geurts@vu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Reappointed 2nd term from 15 Jan 2026. Source: vu.nl'},
  {id:'c007',instId:'vu',first:'Margrethe',last:'Jonkman',title:'President of the Executive Board',dept:'Executive Board',email:'m.j.jonkman@vu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'President since 1 Nov 2023. Source: vu.nl'},
  {id:'c008',instId:'vu',first:'Hilde',last:'van Wijngaarden',title:'Director University Library',dept:'University Library (UB VU)',email:'h.n.van.wijngaarden@vu.nl',phone:'+31 20 59 85145',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: vu.nl/university-library'},
  {id:'c009',instId:'vu',first:'Joeri',last:'Both',title:'Head of Research Support',dept:'University Library (UB VU)',email:'j.both@vu.nl',phone:'+31 6 1101 5918',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: vu.nl/university-library'},
  {id:'c010',instId:'leiden',first:'Luc',last:'Sels',title:'President of the Executive Board',dept:'Executive Board',email:'l.sels@leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'1st term 1 Nov 2025–31 Oct 2029. Former Rector of KU Leuven. Source: universiteitleiden.nl'},
  {id:'c011',instId:'leiden',first:'Sarah',last:'de Rijcke',title:'Rector Magnificus',dept:'Executive Board',email:'s.de.rijcke@leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'1st term 15 Jan 2026. Education, research, open science. Source: universiteitleiden.nl'},
  {id:'c012',instId:'leiden',first:'Timo',last:'Kos',title:'Vice President of the Executive Board',dept:'Executive Board',email:'t.kos@leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'1st term 1 Mar 2025. Finance, HR, ICT, real estate. Source: universiteitleiden.nl'},
  {id:'c013',instId:'leiden',first:'Kurt',last:'De Belder',title:'University Librarian & Director',dept:'Leiden University Libraries (UBL)',email:'k.de.belder@library.leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Director since 2013, also Director of Leiden University Press. Source: universiteitleiden.nl'},
  {id:'c014',instId:'leiden',first:'Heleen',last:'Palmen',title:'Open Access Contact, Centre for Digital Scholarship',dept:'Leiden University Libraries - CDS',email:'h.palmen@library.leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: library.universiteitleiden.nl'},
  {id:'c015',instId:'leiden',first:'Femmy',last:'Admiraal',title:'Research Data Manager, Centre for Digital Scholarship',dept:'Leiden University Libraries - CDS',email:'f.admiraal@library.leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: library.universiteitleiden.nl'},
  {id:'c016',instId:'tudelft',first:'Ingrid',last:'Thijssen',title:'President of the Executive Board',dept:'Executive Board',email:'i.d.thijssen@tudelft.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'1st term: 1 Mar 2026–1 Mar 2030. Source: tudelft.nl'},
  {id:'c017',instId:'tudelft',first:'Hester',last:'Bijl',title:'Rector Magnificus',dept:'Executive Board',email:'h.bijl@tudelft.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'1st term: 15 Jan 2026. Previously Rector at Leiden. Source: tudelft.nl'},
  {id:'c018',instId:'tudelft',first:'Nick',last:'Bos',title:'Vice President Operations',dept:'Executive Board',email:'n.j.p.m.bos@tudelft.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Term: 1 Aug 2025–1 Feb 2027. Source: tudelft.nl'},
  {id:'c019',instId:'tudelft',first:'Irene',last:'Haslinger',title:'Director TU Delft Library',dept:'TU Delft Library',email:'I.M.Haslinger@tudelft.nl',phone:'+31 15 27 85678',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tudelft.nl/library'},
  {id:'c020',instId:'tudelft',first:'Alastair',last:'Dunning',title:'Head of Library Research Services',dept:'TU Delft Library',email:'A.C.Dunning@tudelft.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Oversees 4TU.ResearchData, Research Data, Scholarly Communications. Source: tudelft.nl/library'},
  {id:'c021',instId:'eur',first:'Annelien',last:'Bredenoord',title:'President of the Executive Board',dept:'Executive Board',email:'a.bredenoord@eur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Chair since 1 Sep 2024. Source: eur.nl'},
  {id:'c022',instId:'eur',first:'Jantine',last:'Schuit',title:'Rector Magnificus',dept:'Executive Board',email:'j.schuit@eur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 1 Nov 2024. Oversees education, research, research information. Source: eur.nl'},
  {id:'c023',instId:'eur',first:'Ellen',last:'van Schoten',title:'Vice-President of the Executive Board',dept:'Executive Board',email:'e.vanschoten@eur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'VP since 1 Jan 2021. Finance, ICT, sustainability. Source: eur.nl'},
  {id:'c024',instId:'eur',first:'Lucinda',last:'Jones',title:'Director University Library',dept:'Erasmus University Library',email:'lucinda.jones@eur.nl',phone:'+31 10 754 52 11',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: eur.nl/library'},
  {id:'c025',instId:'eur',first:'Diddel',last:'Francissen',title:'Head of Library Research Support',dept:'Erasmus University Library',email:'diddel.francissen@eur.nl',phone:'+31 6 14 97 64 78',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Responsible for research support at faculties. Source: eur.nl/library'},
  {id:'c026',instId:'eur',first:'Andrea',last:'Tarchi',title:'Publication Support Team Leader',dept:'Erasmus University Library',email:'andrea.tarchi@eur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Open Science, copyright, Open Access, research information systems for EUR and Erasmus MC. Source: eur.nl/library'},
  {id:'c027',instId:'uu',first:'Hans',last:'Brug',title:'President of the Executive Board',dept:'Executive Board',email:'j.brug@uu.nl',phone:'+31 6 28910683',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 1 Jan 2026. Strategy, HR, external relations. Source: uu.nl'},
  {id:'c028',instId:'uu',first:'Wilco',last:'Hazeleger',title:'Rector Magnificus',dept:'Executive Board',email:'w.hazeleger@uu.nl',phone:'+31 6 34128716',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 27 Mar 2025. Education, research, academic integrity. Source: uu.nl'},
  {id:'c029',instId:'uu',first:'Margot',last:'van der Starre',title:'Vice President of the Executive Board',dept:'Executive Board',email:'m.vanderstarre@uu.nl',phone:'+31 6 34387784',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'VP since 15 Mar 2021. Finance, ICT, campus. Source: uu.nl'},
  {id:'c030',instId:'uu',first:'Ted',last:'Sanders',title:'Vice Rector for Research',dept:'Executive Board',email:'t.j.m.sanders@uu.nl',phone:'+31 6 34 161 057',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'VP Research since 1 Jun 2024. Research strategy, Open Science, Recognition & Rewards. Source: uu.nl'},
  {id:'c031',instId:'uu',first:'Matthijs',last:'van Otegem',title:'Director of Utrecht University Library',dept:'Utrecht University Library',email:'m.v.otegem@uu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Director since 1 Oct 2022. Source: uu.nl'},
  {id:'c032',instId:'wur',first:'Sjoukje',last:'Heimovaara',title:'President of the Executive Board',dept:'Executive Board',email:'sjoukje.heimovaara@wur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'President since 1 Jul 2022. Source: wur.nl'},
  {id:'c033',instId:'wur',first:'Carolien',last:'Kroeze',title:'Rector Magnificus & Vice-President',dept:'Executive Board',email:'carolien.kroeze@wur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 10 Mar 2024. Source: wur.nl'},
  {id:'c034',instId:'wur',first:'Peter',last:'Ploegsma',title:'Member of the Executive Board',dept:'Executive Board',email:'peter.ploegsma@wur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'From 1 Nov 2025. Finance, infrastructure. Source: wur.nl'},
  {id:'c035',instId:'wur',first:'Martine',last:'Pronk',title:'Head Librarian / Library Director',dept:'WUR Library',email:'martine.pronk@wur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'In post from 1 Mar 2026, first woman in this role at WUR. Source: wur.nl'},
  {id:'c036',instId:'rug',first:'Jouke',last:'de Vries',title:'President of the Board of the University',dept:'Executive Board',email:'jouke.de.vries@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'President since 1 Sep 2023. Source: rug.nl'},
  {id:'c037',instId:'rug',first:'Jacquelien',last:'Scherpen',title:'Rector Magnificus',dept:'Executive Board',email:'j.m.a.scherpen@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Rector since 1 Sep 2023. Education, research, internationalisation. Source: rug.nl'},
  {id:'c038',instId:'rug',first:'Marjolein',last:'Nieboer',title:'Director of University Library',dept:'University Library (RUG)',email:'marjolein.nieboer@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Director since 2010, first woman in this role. Source: rug.nl'},
  {id:'c039',instId:'rug',first:'Nolda',last:'Tipping-Griffioen',title:'Director of ICT / CIO',dept:'Center for Information Technology (CIT)',email:'n.tipping-griffioen@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'CIO and Director CIT since 1 Jul 2024. Source: rug.nl'},
  {id:'c040',instId:'ru',first:'Alexandra',last:'van Huffelen',title:'President of the Executive Board',dept:'Executive Board',email:'a.vanhuffelen@ru.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'President since 1 Feb 2025. Strategy, alumni, impact. Source: ru.nl'},
  {id:'c041',instId:'ru',first:'José',last:'Sanders',title:'Rector Magnificus',dept:'Executive Board',email:'j.m.sanders@ru.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'60th Rector since 17 Oct 2023. Education, research, student affairs. Source: ru.nl'},
  {id:'c042',instId:'ru',first:'Marcel',last:'Wintels',title:'Interim Vice President of the Executive Board',dept:'Executive Board',email:'m.wintels@ru.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Interim VP from 5 Jan 2026. Source: ru.nl'},
  {id:'c043',instId:'ru',first:'Iwan',last:'Holleman',title:'Director of University Library',dept:'Radboud University Library',email:'i.holleman@ru.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: ru.nl'},
  {id:'c044',instId:'um',first:'Pamela',last:'Habibović',title:'Interim Chair of the Executive Board',dept:'Executive Board',email:'pamela.habibovic@maastrichtuniversity.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Interim from 1 Mar 2026 for 6 months, following Rianne Letschert becoming minister. Source: maastrichtuniversity.nl'},
  {id:'c045',instId:'um',first:'Jan',last:'Smits',title:'Interim Rector Magnificus',dept:'Executive Board',email:'jan.smits@maastrichtuniversity.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Interim Rector from 1 Mar 2026. Source: maastrichtuniversity.nl'},
  {id:'c046',instId:'um',first:'Jan-Tjitte',last:'Meindersma',title:'Vice-Chair of the Executive Board',dept:'Executive Board',email:'jantjitte.meindersma@maastrichtuniversity.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: maastrichtuniversity.nl'},
  {id:'c047',instId:'um',first:'Claudia',last:'van Oppen',title:'Director University Library',dept:'Maastricht University Library',email:'claudia.vanoppen@maastrichtuniversity.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: maastrichtuniversity.nl'},
  {id:'c048',instId:'tiu',first:'Wim',last:'van de Donk',title:'Rector Magnificus & President',dept:'Executive Board',email:'w.b.h.j.vddonk@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Rector Magnificus and President, reappointed Oct 2024 for 2nd term. Source: tilburguniversity.edu'},
  {id:'c049',instId:'tiu',first:'Antoinette',last:'de Bont',title:'Vice-Rector Magnificus',dept:'Executive Board',email:'a.debont@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Vice-Rector Magnificus since 1 Sep 2025. Source: tilburguniversity.edu'},
  {id:'c050',instId:'tiu',first:'Wilma',last:'de Koning',title:'Vice-President of the Executive Board',dept:'Executive Board',email:'w.dekoning@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: tilburguniversity.edu'},
  {id:'c051',instId:'tiu',first:'Corné',last:'van Nispen',title:'Director University Library',dept:'Tilburg University Library',email:'c.vannispen@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: librarytechnology.org'},
  {id:'c052',instId:'tue',first:'Koen',last:'Janssen',title:'President of the Executive Board',dept:'Executive Board',email:'k.j.m.janssen@tue.nl',phone:'+31 40 247 9111',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'President since 1 Mar 2025. Source: tue.nl'},
  {id:'c053',instId:'tue',first:'Silvia',last:'Lenaerts',title:'Rector Magnificus',dept:'Executive Board',email:'s.lenaerts@tue.nl',phone:'+31 40 247 9111',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'First woman Rector at TU/e. Source: tue.nl'},
  {id:'c054',instId:'tue',first:'Patrick',last:'Groothuis',title:'Vice-President of the Executive Board',dept:'Executive Board',email:'p.j.m.groothuis@tue.nl',phone:'+31 40 247 9111',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Vice-President since 1 Nov 2023. Source: tue.nl'},
  {id:'c055',instId:'tue',first:'Corry',last:'Wouters',title:'Director Library & Information Services / CIO',dept:'Library and Information Services (LIS)',email:'c.wouters@tue.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Combined library and CIO function. Source: tue.nl'},
  {id:'c056',instId:'tue',first:'Sonja',last:'Vos-Poppelaars',title:'Director of Research Support & Valorization',dept:'Research Support & Valorization',email:'s.j.w.vos@tue.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tue.nl'},
  {id:'c057',instId:'ut',first:'Tom',last:'Veldkamp',title:'Rector Magnificus',dept:'Executive Board',email:'t.veldkamp@utwente.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Rector since 27 Nov 2020, reappointed Oct 2024. Source: utwente.nl'},
  {id:'c058',instId:'ut',first:'Machteld',last:'Roos',title:'Vice-President of the Executive Board',dept:'Executive Board',email:'m.roos@utwente.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: utwente.nl'},
  {id:'c059',instId:'ut',first:'Mert',last:'Alberts',title:'Director LISA / CIO',dept:'Library, ICT Services & Archive (LISA)',email:'l.k.alberts@utwente.nl',phone:'+31 53 489 4001',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Combined library, IT, archive division. Source: utwente.nl'},
  {id:'c060',instId:'ut',first:'Nicole',last:'Loorbach',title:'Open Access Specialist',dept:'Library, ICT Services & Archive (LISA)',email:'n.r.loorbach@utwente.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Source: utwente.nl'},
  {id:'c061',instId:'ut',first:'Lineke',last:'Klunder-Roepers',title:'Research Information Specialist',dept:'Library, ICT Services & Archive (LISA)',email:'d.m.roepers@utwente.nl',phone:'+31 53 489 2065',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'UT Research Information. Source: utwente.nl'},
  {id:'c062',instId:'ou',first:'Nicole',last:'Ummelen',title:'Executive Chairman',dept:'Executive Board',email:'n.ummelen@ou.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Executive Chairman since 1 Sep 2023. Source: ou.nl'},
  {id:'c063',instId:'ou',first:'Ellen',last:'Van den Poel',title:'Rector Magnificus',dept:'Executive Board',email:'e.vandenpoel@ou.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Rector since 1 Jan 2024. Source: ou.nl'},
  {id:'c064',instId:'vu',first:'Sander',last:'Bosch',title:'Open Science Coordinator',dept:'University Library (UB VU)',email:'s.bosch@vu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Open Science coordination. Source: vu.nl/library'},
  {id:'c065',instId:'vu',first:'Marcel',last:'Ras',title:'Coordinator Research Data Support',dept:'University Library (UB VU)',email:'m.ras@vu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Network Research Data Support coordinator. Source: vu.nl/library'},
  {id:'c066',instId:'vu',first:'Matthijs',last:'de Zwaan',title:'Coordinator Research Intelligence',dept:'University Library (UB VU)',email:'researchintelligence.ub@vu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Team Research Intelligence. Team email confirmed. Source: vu.nl/library'},
  {id:'c067',instId:'leiden',first:'Alenka',last:'Princic',title:'Head of Centre for Digital Scholarship',dept:'Leiden University Libraries - CDS',email:'a.princic@library.leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Heads CDS — research data, digital humanities, open science. Source: library.universiteitleiden.nl'},
  {id:'c068',instId:'leiden',first:'Karlijn',last:'Hermans',title:'Open Science Coordinator',dept:'Leiden University Libraries',email:'k.hermans@library.leidenuniv.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Open Science coordination. Source: library.universiteitleiden.nl'},
  {id:'c069',instId:'tudelft',first:'Yan',last:'Wang',title:'Head of Research Data and Software Management',dept:'TU Delft Library',email:'Y.Wang-16@tudelft.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Leads FAIR data and research software management. Source: tudelft.nl/library'},
  {id:'c070',instId:'uu',first:'Wenneke',last:'Meerstadt',title:'Head of Publishing Support',dept:'Utrecht University Library',email:'w.meerstadt@uu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Scholarly communication, Open Access publishing support. Source: uu.nl/library'},
  {id:'c071',instId:'uu',first:'Stefan',last:'Einarson',title:'Head of Research Data Support',dept:'Utrecht University Library',email:'s.einarson@uu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Research data management and support. Source: uu.nl/library'},
  {id:'c072',instId:'uu',first:'Marianne',last:'Renkema',title:'Head of Information Management',dept:'Utrecht University Library',email:'m.renkema@uu.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Research information systems and management. Source: uu.nl/library'},
  {id:'c073',instId:'wur',first:'Ellen',last:'Fest',title:'Head of Research Information and Impact Services',dept:'WUR Library',email:'ellen.fest@wur.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Research information and impact services. Has spoken publicly on future of CRIS. Source: wur.nl/library'},
  {id:'c074',instId:'rug',first:'Martijn',last:'Verwegen',title:'Cluster Director Research & Impact',dept:'University Library (RUG)',email:'m.verwegen@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Most senior research support director at RUG. Source: rug.nl'},
  {id:'c075',instId:'rug',first:'Maarten',last:'Schunselaar',title:'Head of Talent, Funding & Quality',dept:'Research Services',email:'m.schunselaar@rug.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Talent, funding and research quality. Source: rug.nl'},
  {id:'c076',instId:'ru',first:'Charlotte',last:'Burgers-de Klein',title:'Project Manager CRIS / Research Information',dept:'Research Information Management',email:'charlotte.burgers@ru.nl',phone:'+31 6 500 85 212',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Managing Vidatum CRIS migration — key contact for Elsevier research systems. Source: ru.nl'},
  {id:'c077',instId:'ru',first:'Dirk',last:'van Gorp',title:'Open Science Officer',dept:'Research Support',email:'d.vangorp@ru.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Open Science policy and implementation. Source: ru.nl'},
  {id:'c078',instId:'um',first:'Pedro',last:'Hernandez Serrano',title:'Coordinator Data Stewardship Services',dept:'Maastricht University Library',email:'p.hernandez@maastrichtuniversity.nl',phone:'',linkedin:'',research:'',status:'active',priority:'medium',quality:'verified',lastContact:'',notes:'Data stewardship coordination. Source: maastrichtuniversity.nl'},
  {id:'c079',instId:'tiu',first:'Suzanne',last:'Jongman',title:'Head of Grant Support',dept:'Research Support Office',email:'s.jongman@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Grants and research funding support. Source: tilburguniversity.edu'},
  {id:'c080',instId:'tiu',first:'Wilma',last:'Paffen',title:'Pure Coordinator / Open Access Coordinator',dept:'Tilburg University Library',email:'w.paffen@tilburguniversity.edu',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Pure CRIS and Open Access coordination — key for Elsevier Pure/SciVal. Source: tilburguniversity.edu'},
  {id:'c081',instId:'ut',first:'Atilla',last:'Kerpisci',title:'Managing Director Strategic Business Development',dept:'Research & Impact',email:'a.kerpisci@utwente.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Strategic research development. Source: utwente.nl'},
  {id:'c082',instId:'ut',first:'Telma',last:'Esteves',title:'Team Lead Grants Office',dept:'Research Support',email:'t.esteves@utwente.nl',phone:'',linkedin:'',research:'',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Leads grants office and research funding applications. Source: utwente.nl'},
  {id:'c083',instId:'vu',first:'Matteo',last:'Iannuzzi',title:'Vice-Dean Research, Faculty of Science',dept:'Faculty of Science',email:'m.iannuzzi@vu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: vu.nl/faculty-science'},
  {id:'c084',instId:'vu',first:'Andreas',last:'Daffertshofer',title:'Vice-Dean Research, Faculty of Behavioural & Movement Sciences',dept:'Faculty of Behavioural & Movement Sciences',email:'a.daffertshofer@vu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: vu.nl/fgb'},
  {id:'c085',instId:'vu',first:'Joost',last:'Deken',title:'Vice-Dean Research, School of Business & Economics',dept:'School of Business & Economics',email:'j.c.deken@vu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: vu.nl/sbe'},
  {id:'c086',instId:'uu',first:'Pita',last:'Berkers',title:'Vice-Dean Research, Faculty of Veterinary Medicine',dept:'Faculty of Veterinary Medicine',email:'p.berkers@uu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: uu.nl/faculty-vet-medicine'},
  {id:'c087',instId:'uu',first:'Roos',last:'Masereeuw',title:'Vice-Dean Research, Faculty of Science',dept:'Faculty of Science',email:'r.masereeuw@uu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: uu.nl/faculty-science'},
  {id:'c088',instId:'uu',first:'Jan',last:'Hassink',title:'Vice-Dean Research, Utrecht University School of Economics',dept:'Utrecht University School of Economics (USE)',email:'j.hassink@uu.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: uu.nl/use'},
  {id:'c089',instId:'wur',first:'Edith',last:'Feskens',title:'Dean of Research',dept:'Research & Innovation',email:'edith.feskens@wur.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: wur.nl/research'},
  {id:'c090',instId:'eur',first:'Semiha',last:'Denktaş',title:'Vice-Dean Research, Erasmus School of Social & Behavioural Sciences',dept:'ESSB',email:'semiha.denktaş@eur.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: eur.nl/essb'},
  {id:'c091',instId:'ru',first:'Tom',last:'Heskes',title:'Vice-Dean Research, Faculty of Science',dept:'Faculty of Science',email:'t.heskes@ru.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: ru.nl/faculty-science'},
  {id:'c092',instId:'rug',first:'Joost',last:'Frenken',title:'Dean, Faculty of Science & Engineering',dept:'Faculty of Science & Engineering',email:'j.w.m.frenken@rug.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Holds research portfolio for FSE. Source: rug.nl/fse'},
  {id:'c093',instId:'ut',first:'Mariolein',last:'Koeva',title:'Portfolio Holder Research, Faculty ITC',dept:'Faculty of Geo-Information Science & Earth Obs. (ITC)',email:'m.koeva@utwente.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: utwente.nl/itc'},
  {id:'c094',instId:'ut',first:'Mariëlle',last:'Stoelinga',title:'Portfolio Holder Research, Faculty EEMCS',dept:'Faculty of Electrical Engineering, Maths & CS (EEMCS)',email:'m.stoelinga@utwente.nl',phone:'+31 53 489 3774',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Email and phone confirmed from faculty board page. Source: utwente.nl/eemcs'},
  {id:'c095',instId:'tue',first:'Guus',last:'Pemen',title:'Vice-Dean Research, Department of Electrical Engineering',dept:'Electrical Engineering',email:'g.j.h.pemen@tue.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tue.nl/ee'},
  {id:'c096',instId:'leiden',first:'Jan',last:'Knoester',title:'Dean, Faculty of Science',dept:'Faculty of Science',email:'j.knoester@physics.leidenuniv.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: universiteitleiden.nl/science'},
  {id:'c097',instId:'leiden',first:'Janine',last:'Ubink',title:'Director of Research, Faculty of Law',dept:'Faculty of Law',email:'j.m.ubink@law.leidenuniv.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: universiteitleiden.nl/law'},
  {id:'c098',instId:'tiu',first:'Joerg',last:'Knoben',title:'VP Research, Tilburg School of Economics & Management',dept:'TiSEM',email:'j.knoben@tilburguniversity.edu',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tilburguniversity.edu/tisem'},
  {id:'c099',instId:'tiu',first:'Jitske',last:'Šafář Postma',title:'VP Research, Tilburg School of Humanities & Digital Sciences',dept:'TSHD',email:'j.safarpostma@tilburguniversity.edu',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tilburguniversity.edu/tshd'},
  {id:'c100',instId:'tiu',first:'Thomas',last:'Kooij',title:'VP Research, Tilburg School of Social & Behavioural Sciences',dept:'TSB',email:'t.kooij@tilburguniversity.edu',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: tilburguniversity.edu/tsb'},
  {id:'c101',instId:'aumc',first:'Elga',last:'de Vries',title:'Vice Dean of Research',dept:'Amsterdam UMC',email:'e.devries@amsterdamumc.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed June 2024. Source: amsterdamumc.nl'},
  {id:'c102',instId:'umcutrecht',first:'Elly',last:'Hol',title:'Vice-Dean of Research',dept:'UMC Utrecht',email:'e.hol@umcutrecht.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 2024. Source: umcutrecht.nl'},
  {id:'c103',instId:'erasmusmc',first:'Stefan',last:'Sleijfer',title:'Dean of Research',dept:'Erasmus MC',email:'s.sleijfer@erasmusmc.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Dean holding research portfolio. Source: erasmusmc.nl'},
  {id:'c104',instId:'radboudumc',first:'Jan',last:'Smit',title:'Dean & Vice Chair (Research)',dept:'Radboud UMC',email:'jan.smit@radboudumc.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: radboudumc.nl'},
  {id:'c105',instId:'mumc',first:'Manon',last:'van Engeland',title:'Scientific Director',dept:'MUMC+ Research',email:'m.vanengeland@mumc.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: mumc.nl'},
  {id:'c106',instId:'umcg',first:'Jochen',last:'Mierau',title:'Vice-Dean of Research',dept:'UMCG',email:'j.mierau@umcg.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Prodecaan Onderzoek. Source: umcg.nl'},
  {id:'c107',instId:'nki',first:'Thijn',last:'Brummelkamp',title:'Scientific Director',dept:'Netherlands Cancer Institute',email:'t.brummelkamp@nki.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nki.nl'},
  {id:'c108',instId:'nki',first:'Jacco',last:'van Rheenen',title:'Deputy Scientific Director',dept:'Netherlands Cancer Institute',email:'j.vanrheenen@nki.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nki.nl'},
  {id:'c109',instId:'hubrecht',first:'Geert',last:'Kops',title:'Director',dept:'Hubrecht Institute',email:'g.kops@hubrecht.eu',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Director since Sept 2023. Source: hubrecht.eu'},
  {id:'c110',instId:'nin',first:'Christiaan',last:'Levelt',title:'Director',dept:'Netherlands Institute for Neuroscience',email:'c.levelt@nin.knaw.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Director since Jan 2024. Source: nin.knaw.nl'},
  {id:'c111',instId:'cwi',first:'Vanessa',last:'Evers',title:'Director',dept:'CWI',email:'v.evers@cwi.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: cwi.nl'},
  {id:'c112',instId:'nikhef',first:'Jorgen',last:'D\'Hondt',title:'Director',dept:'Nikhef',email:'j.dhondt@nikhef.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nikhef.nl'},
  {id:'c113',instId:'sron',first:'Michael',last:'Wise',title:'General & Scientific Director',dept:'SRON Netherlands Institute for Space Research',email:'m.wise@sron.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Second term. Source: sron.nl'},
  {id:'c114',instId:'nwo',first:'Marcel',last:'Levi',title:'President',dept:'NWO',email:'m.levi@nwo.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nwo.nl'},
  {id:'c115',instId:'nwo',first:'Mirjam',last:'de Boer',title:'Domain Chair, Science (ENW)',dept:'NWO',email:'m.deboer@nwo.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nwo.nl'},
  {id:'c116',instId:'nwo',first:'Michiel',last:'Voûte',title:'Domain Chair, Applied & Engineering Sciences (TTW)',dept:'NWO',email:'m.voute@nwo.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: nwo.nl'},
  {id:'c117',instId:'knaw',first:'Marileen',last:'Dogterom',title:'President',dept:'KNAW',email:'m.dogterom@knaw.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: knaw.nl'},
  {id:'c118',instId:'knaw',first:'Gijs',last:'de Snoo',title:'Director Research Policy',dept:'KNAW',email:'g.desnoo@knaw.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: knaw.nl'},
  {id:'c119',instId:'rivm',first:'Isabel',last:'Arends',title:'Director General',dept:'RIVM',email:'i.arends@rivm.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed April 2026. Source: rivm.nl'},
  {id:'c120',instId:'tno',first:'Christa',last:'Hooijer',title:'Chief Scientist',dept:'TNO',email:'christa.hooijer@tno.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Appointed 2025. Source: tno.nl'},
  {id:'c121',instId:'deltares',first:'Bart',last:'van den Hurk',title:'Scientific Director',dept:'Deltares',email:'bart.vandenhurk@deltares.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: deltares.nl'},
  {id:'c122',instId:'esc',first:'Menno',last:'Rasch',title:'Director',dept:'Netherlands eScience Center',email:'m.rasch@esciencecenter.nl',phone:'',linkedin:'',research:'Research Director',status:'active',priority:'high',quality:'verified',lastContact:'',notes:'Source: esciencecenter.nl'}
];

// Competitor product data — verified from official university library sources (Aug 2026)
// Renewal dates verified from public contracts and library announcements
if (!window.COMP_DATA) {
  window.COMP_DATA = {
    uva: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'yes', scivalRenewal:'Dec 2026', scivalProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      pure:'yes', pureRenewal:'', pureProof:'https://uba.uva.nl/en/support/research/registering-research/registering-research.html',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I887064364',
    },
    vu: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'',
      wos:'cancelled', wosRenewal:'Jan 2026', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://vu.nl/en/employee/university-library/termination-of-access-to-web-of-science-as-of-january-1-2026',
      proofOpenalex: 'https://openalex.org/institutions/I865915315',
    },
    eur: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://libguides.eur.nl/courseresearchimpacts/webofscience',
      proofOpenalex: 'https://openalex.org/institutions/I913958620',
    },
    uu: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://research-portal.uu.nl/',
      wos:'cancelled', wosRenewal:'Jan 2026', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://students.uu.nl/en/news/access-to-web-of-science-will-end-on-1-january-2026',
      proofOpenalex: 'https://openalex.org/institutions/I193662353',
    },
    leiden: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.library.universiteitleiden.nl/researchers/lucris-and-scholarly-publications',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.library.universiteitleiden.nl/searching-sources',
      proofOpenalex: 'https://openalex.org/institutions/I121797337',
    },
    rug: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://www.rug.nl/library/support/pure/about-pure/?lang=en',
      wos:'expiring', wosRenewal:'Dec 2026', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.rug.nl/library/news/20260420-end-web-of-science?lang=en',
      proofOpenalex: 'https://openalex.org/institutions/I169381384',
    },
    ru: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.ru.nl/en/staff/news/tender-for-new-cris-completed',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.ru.nl/en/services/library/searching-for-literature/databases/web-of-science',
      proofOpenalex: 'https://openalex.org/institutions/I145872427',
    },
    tudelft: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'',
      wos:'cancelled', wosRenewal:'Jan 2026', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      openalexTier:'Member', openalexFee:'$5,000/yr',
      proofWos: 'https://www.tudelft.nl/en/2025/library/access-to-web-of-science-and-journal-citation-reports-will-end-on-1-january-2026',
      proofOpenalex: 'https://github.com/ourresearch/town-hall-notes/blob/main/2026-07-09-cab/retro.md',
    },
    tue: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://research.tue.nl/',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.tue.nl/en/our-university/library/resources/databases',
      proofOpenalex: 'https://openalex.org/institutions/I83019370',
    },
    ut: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://www.utwente.nl/en/service-portal/research-support/pure-research-information-system',
      wos:'cancelled', wosRenewal:'Dec 2025', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.utwente.nl/en/education/student-services/news-events/news/2025/11/622976/web-of-science-licence-will-end-on-31-december-2025',
      proofOpenalex: 'https://openalex.org/institutions/I94624287',
    },
    tiu: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://www.tilburguniversity.edu/campus/university-library/searching-information/tilburg-university-research-portal',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.tilburguniversity.edu/campus/university-library/events/workshop-web-science',
      proofOpenalex: 'https://openalex.org/institutions/I193700539',
    },
    um: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://cris.maastrichtuniversity.nl/',
      wos:'yes', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      openalexTier:'Partner', openalexFee:'Custom pricing',
      proofWos: 'https://library.maastrichtuniversity.nl/database/web/',
      proofOpenalex: 'https://library.maastrichtuniversity.nl/news/investing-in-open-research-information-openalex-partnership-and-end-of-scopus-license/',
    },
    wur: {
      scopus:'yes', scopusRenewal:'Dec 2026', scopusProof:'https://www.universiteitenvannederland.nl/en/current/news/dutch-research-institutions-and-elsevier-announce-new-agreements',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://research.wur.nl/',
      wos:'no', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: 'https://www.wur.nl/en/library/databases-and-collections',
      proofOpenalex: 'https://openalex.org/institutions/I913481162',
    },
    ou: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://research.ou.nl/',
      wos:'unknown', wosRenewal:'', openalex:'free',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '',
      proofOpenalex: 'https://openalex.org/institutions/I7876267',
    },
    aumc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://www.amsterdamumc.org/en/about/organization/one-pure-system-for-all-of-amsterdam-umc',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    erasmusmc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://medbib.erasmusmc.nl/en/publishing/pure-our-new-research-information-system/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    umcutrecht: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://researchinformation.umcutrecht.nl/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    umcg: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://libguides.rug.nl/PureUMCG/Portal',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    mumc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://library.maastrichtuniversity.nl/database/umarchive/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    maxima: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'yes', pureRenewal:'', pureProof:'https://pure.prinsesmaximacentrum.nl/en/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    lumc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.library.universiteitleiden.nl/researchers/lucris-and-scholarly-publications',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'yes', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    radboudumc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'no', pureRenewal:'', pureProof:'https://www.ru.nl/en/staff/news/tender-for-new-cris-completed',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'no', symplectic:'no',
      proofWos: '', proofOpenalex: '',
    },
    nki: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'unknown', pureRenewal:'', pureProof:'https://www.nki.nl/research/find-a-researcher/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    mmc: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'unknown', pureRenewal:'', pureProof:'https://www.mmc.nl/over-ons/wetenschap',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    sanquin: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'unknown', pureRenewal:'', pureProof:'https://www.sanquin.nl/en/research',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    aighd: {
      scopus:'unknown', scopusRenewal:'', scopusProof:'',
      scival:'unknown', scivalRenewal:'', scivalProof:'',
      pure:'unknown', pureRenewal:'', pureProof:'https://publications.aighd.org/',
      wos:'unknown', wosRenewal:'', openalex:'unknown',
      dimensions:'unknown', converis:'unknown', symplectic:'unknown',
      proofWos: '', proofOpenalex: '',
    },
    nwo:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nwo.nl/en/what-does-the-dutch-research-council-do', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    tno:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://repository.tno.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    knaw:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    hubrecht:   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/hubrecht-institute/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nin:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/netherlands-institute-for-neuroscience-nin/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rivm:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://rivm.openrepository.com/rivm/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    cwi:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://ir.cwi.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    esc:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://research-software-directory.org/organisations/netherlands-escience-center', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    deltares:   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.deltares.nl/en/expertise/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    sron:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.sron.nl/scientific-publications/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nikhef:     { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.nikhef.nl/nikhef-nwo-i-open-access/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    astron:     { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.astron.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nioz:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.nioz.nl/en/research/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    knmi:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.knmi.nl/research/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    naturalis:  { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://repository.naturalis.nl/about', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nlr:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://reports.nlr.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    pbl:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.pbl.nl/en/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    cpb:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.cpb.nl/en', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    rathenau:   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/rathenau-institute/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    scp:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://repository.scp.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    clingendael:{ scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.clingendael.org/research', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    hiil:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.hiil.org/who-we-are/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    oxfamnovib: { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://oxfamilibrary.openrepository.com/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    icj:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.icj-cij.org/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    iiss:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.asser.nl/about-the-asser-institute/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    zonmw:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.zonmw.nl/en/open-access-background', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    niod:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/niod-institute-for-war-holocaust-and-genocide-studies/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    huygens:    { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/huygens-instituut/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    iish:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/iish/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    meertens:   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/meertens-instituut-nederlandse-etnologie/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    dans:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/dans-knaw/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nioo:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/netherlands-institute-of-ecology-nioo-knaw/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    westerdijk: { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'yes',pureRenewal:'',pureProof:'https://pure.knaw.nl/portal/en/organisations/westerdijk-instituut/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    amolf:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nwo-i.nl/en/nwo-institutes-organisation/nwo-institutes/amolf/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    arcnl:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://arcnl.nl/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    differ:     { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.differ.nl/research', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    marin:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.marin.nl/en/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nfi:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nature.com/nature-index/institution-outputs/netherlands/netherlands-forensic-institute-nfi/51904071140ba0d852000000', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    wodc:       { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'no',pureRenewal:'',pureProof:'https://www.atmire.com/articles/detail/dutch-ministry-of-justice-and-security-migrates-to-open-repository', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    trimbos:    { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.trimbos.nl/english/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    nivel:      { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.nivel.nl/en/about-nivel', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    ihedelft:   { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.un-ihe.org/research', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    mpi:        { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.mpi.nl/publications', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
    wetsus:     { scopus:'unknown',scopusRenewal:'',scopusProof:'', scival:'unknown',scivalRenewal:'',scivalProof:'', pure:'unknown',pureRenewal:'',pureProof:'https://www.wetsus.nl/about-wetsus/', wos:'unknown',wosRenewal:'',openalex:'unknown', dimensions:'unknown',converis:'unknown',symplectic:'unknown', proofWos:'',proofOpenalex:'' },
  };
}
